### ISSUE TITLE
watchdog not feeded on boot

### ISSUE THREAD

**Issue by rubenverhoef** [rubenverhoef/OAP-Config#58]
sometimes the watchdog is not getting feeded.

**Comment by rubenverhoef** [comment]
it is because of the radio_cli, it is getting stuck in the loop for getting time

**Comment by rubenverhoef** [comment]
https://stackoverflow.com/questions/20017805/bash-capture-output-of-command-run-in-background

**Comment by linuxchris12** [comment]
Maybe I can help here. Which command is getting stuck exactly? I checked the datetime command of radio_cli, but I don't see a point where it could get stuck, only if the hardware SPI or some very low os SPI functions would not work properly.

**Comment by rubenverhoef** [comment]
Nice to meet you over here!

Well it get stuck to get the time from the DAB https://github.com/rubenverhoef/OAP-Config/blob/6ead6cb42a8eec42294eacd66c0df03e9de6fec5/scripts/service_OAP_startup.sh#L142
Maybe it does not get stuck but it will bring the whole loop to more than 16 seconds (the WatchDog time).

I think it has something to do with calling also the radio_cli from other scripts. So it can be at the same time and i don't kill it here before executing it. Like i do over here: https://github.com/rubenverhoef/OAP-Config/blob/6ead6cb42a8eec42294eacd66c0df03e9de6fec5/scripts/service_OAP_startup.sh#L39

But i have to fix #59 first, now i have just disable the time getting from the loop.

**Comment by linuxchris12** [comment]
I did not go into detail, but my first idea is:

did you tune to a DAB ensemble before using the -t command to get the time?
Because: without beeing tuned to a DAB ensemble, the Si468x does not have a time.
It needs DAB to get the current time, otherwise, the command will fail.

I see that you boot the Si468x and load a firmware before, but you dont tune to a DAB ensemble.
